# Lock down dist to ensure that builds run on a distribution that supports oraclejdk8
dist: trusty
language: ruby
jdk:
  - oraclejdk8
rvm:
  - 2.3.1
install:
  - rvm use 2.3.1
  - gem install bundler
  - bundle install
  - git clone --depth 1 https://github.com/endless-sky/endless-sky.git
script: buildr clean package ENDLESS_SKY_DIR=endless-sky
git:
  depth: 10
